### ISSUE TITLE
pip release only includes reqif2html and reqif2xlsx

### ISSUE THREAD

**Issue by ottersity** [ebroecker/pyreqif#23]
Hello,
first of all thank you for this nice tool, it saves me a lot of time.
When i install release 0.6 via pip i don't get the export tools for example `xlsx2reqif.py` is missing. Is this behavior intended?

Best regards,

Philipp

**Comment by ebroecker** [comment]
thanks for this hint.
gonna add it to future releases

**Comment by ebroecker** [comment]
sorry for the delay,

fixed with release 0.7
