### ISSUE TITLE
DateFormat used not compatible with ReqIF standard

### ISSUE THREAD

**Issue by wreggyl** [ebroecker/pyreqif#26]
Hi,

thanks for creating the lib - i really like it. I use it currently to convert xlsx to reqif. I tried to read the generated files in the ALM solution here, but it bring me errors for parsing the date format.

current implementation generates the following format: 2021-02-10T13:20:04.820391

But as described here in the ReqIF standard (https://www.omg.org/spec/ReqIF/1.2/PDF) and here (http://www.w3.org/TR/xmlschema-2/#isoformats) microseconds are not allowed.

as a temporary workaround I change every occurence in create.py 
from: lastChange=datetime.datetime.today().isoformat()
to: datetime.datetime.today().isoformat("T","seconds")

After this change I was able to import the ReqIF, not the ReqIFz, but this is maybe another story.

I think the correct solution would be to use the UTC time as calcualted to my local time? Maybe this issue can be fixed together with: [24](https://github.com/ebroecker/pyreqif/issues/24)

Thanks in advance

**Comment by ebroecker** [comment]
should be fixed in aad81da
