### ISSUE TITLE
last record is missed while using xlsx2reqif.py

### ISSUE THREAD

**Issue by shripadkl123** [ebroecker/pyreqif#27]
[jira1.xlsx](https://github.com/ebroecker/pyreqif/files/5981513/jira1.xlsx)

D:\pyreqif-py3>python xlsx2reqif.py jira1.xlsx
{'IDENTIFIER': '_doc_type_ref', 'LAST-CHANGE': '2021-02-15T17:56:38.169367', 'LONG-NAME': 'doc_type'}

D:\pyreqif-py3>

"jira1.reqifz" file is created. Unzip it and check open jira1.reqif in Notepad++. The record with "ACDS-1" is missing.

**Comment by ebroecker** [comment]
hi @shripadkl123 
thanks, fixed in a0ab825
