### ISSUE TITLE
Add Spec.reqif to the git repository so that others can also run the example.

### ISSUE THREAD

**Issue by bavovanachte** [ebroecker/pyreqif#4]
At the moment, example.py has a file path to Spec.reqif hardcoded. It would be interesting for people trying out the library to make example.py runnable for everyone

**Comment by ebroecker** [comment]
@bavovanachte 

should be fixed now

**Comment by bavovanachte** [comment]
Nice, thanks! Any chance you could also include an example input file? Or are the ones you have confidential?

**Comment by ebroecker** [comment]
I think the old example used this example:

https://reqif.academy/template/traceability-template/

You need to register, but download is free.
