### ISSUE TITLE
Missing dependencies in setup.py

### ISSUE THREAD

**Issue by bavovanachte** [ebroecker/pyreqif#5]

**Comment by bavovanachte** [comment]
When trying to use the script, I'm running into missing dependencies:

- oletools
- xlsxwriter
- lxml

**Comment by ebroecker** [comment]
thanks - gonna add a requirements.txt ...

**Comment by ebroecker** [comment]
fixed with 3f4572b34b6831e858b2808f238bf66669eb8238

currently in iss9 will be fixed soon
