### ISSUE TITLE
Cannot import xlsx as a module

### ISSUE THREAD

**Issue by bavovanachte** [ebroecker/pyreqif#7]
When I try to import xlsx as follows (after installing through pip): 
```python
from pyreqif import xlsx as xml_exporter
```

I get the following warning:

```ModuleNotFoundError: No module named 'extractOleData'```

I managed to fix it by using a relative import in xlsx.py, as follows:

```python
from . import extractOleData
```

**Comment by ebroecker** [comment]
fixed with 3f4572b34b6831e858b2808f238bf66669eb8238

currently in branch iss09, will go mainline soon
